---

- name: Check if role "{{ item.id }}" already exist
  uri:
    url: "{{ api_protocol }}://{{ api_host }}:{{ api_port }}/service/rest/v1/security/roles"
    user: "{{ admin_username }}"
    password: "{{ admin_password }}"
    method: GET
    status_code: 200
    force_basic_auth: true
    ca_path: "{{ root_ca }}"
  no_log: "{{ hide_sensitive_logs }}"
  delegate_to: localhost
  register: existing_roles

- name: Create role "{{ item.id }}"
  uri:
    url: "{{ api_protocol }}://{{ api_host }}:{{ api_port }}/service/rest/v1/security/roles"
    user: "{{ admin_username }}"
    password: "{{ admin_password }}"
    body: "{{ lookup('template','role.json.j2') }}"
    method: POST
    status_code: 200
    force_basic_auth: true
    headers:
      Content-Type: application/json
    body_format: json
    ca_path: "{{ root_ca }}"
  no_log: "{{ hide_sensitive_logs }}"
  register: changes
  changed_when: changes.status == 200
  delegate_to: localhost
  when:
    - item.status != "deleted"
    - item.id not in ( existing_roles | community.general.json_query('json[*].id'))

- name: Sync role "{{ item.id }}" setings
  uri:
    url: "{{ api_protocol }}://{{ api_host }}:{{ api_port }}/service/rest/v1/security/roles/{{ item.id }}"
    user: "{{ admin_username }}"
    password: "{{ admin_password }}"
    body: "{{ lookup('template','role.json.j2') }}"
    method: PUT
    status_code: 204
    force_basic_auth: true
    headers:
      Content-Type: application/json
    body_format: json
    ca_path: "{{ root_ca }}"
  no_log: "{{ hide_sensitive_logs }}"
  register: changes
  changed_when: changes.status == 204
  delegate_to: localhost
  when:
    - item.status != "deleted"
    - item.id in ( existing_roles | community.general.json_query('json[*].id'))

- name: Delete role "{{ item.id }}"
  uri:
    url: "{{ api_protocol }}://{{ api_host }}:{{ api_port }}/service/rest/v1/security/roles/{{ item.id }}"
    user: "{{ admin_username }}"
    password: "{{ admin_password }}"
    method: DELETE
    status_code: 204
    force_basic_auth: true
    ca_path: "{{ root_ca }}"
  no_log: "{{ hide_sensitive_logs }}"
  register: changes
  changed_when: changes.status == 204
  delegate_to: localhost
  when:
    - item.status == "deleted"
    - item.id in ( existing_roles | community.general.json_query('json[*].id'))
